// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"demo/pkg/config"
	"demo/pkg/server"
	"demo/service"
	"demo/service/lobby"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateServer(configPath string) (*server.Server, error) {
	viper, err := config.New(configPath)
	if err != nil {
		return nil, err
	}
	options, err := server.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	getLobby := lobby.NewGetLobby()
	initServicesMap := service.CreateHandlersMap(getLobby)
	serverServer, err := server.New(options, initServicesMap)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}

// wire.go:

/**
 * @Author: Tomonori
 * @Date: 2020/4/22 15:44
 * @Title:
 * --- --- ---
 * @Desc:
 */
var providerSet = wire.NewSet(config.ProviderSet, server.ProviderSet, service.ProviderSet)
