server:
  port: 9000
  multiCore: true
  beatInterval: 10

database:
  user: root
  password: 123456
  host: 127.0.0.1:3306
  db: fuck
  maxIdleConns: 100
  maxOpenConns: 400
  searchUrl: "rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true"
  debug: true

redis:
  host: 127.0.0.1
  port: 6379
  password: a123
  db: 2
  timeout: 5
  expiredTime: 600
